sudo: false
language: node_js
before_install:
- npm install -g npm@latest
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- stable
services:
  - neo4j
notifications:
  slack:
    secure: uJUVpwF6PjT6ry00CSoJOU6sR7jWaB7bqdb03ICitT4Wsisl8XHwHv66vmdiLeNex7NWqwrxG1F912cAORWXTPz5mGMXHZ/ZKKDlYvjEPBnbuPpTnsf1djADamUWE+PPuIKnfDiPjUN1DDoH6VVfnLskes37N/YvOZfjiZ+k4GPm4zAkhY+AZjefx77IAtRdFq3X5sfNkeNutxML5hdIFRkHFLlSPlB/fwOK9f4zgjQgsUZQ7GDlusUIWPsv0W97bgTZy0HGqkgkjxu2VaKWxmhYb8fVNpGE44TNbKwXY2uZcOMpdrAwmlZ7lZ6vQxenwS6fcydPK2y3bxdwpnZCTbxAuiECrWcQotvkj2dH+HYhVmAjAxg0bFEQ9Q2b8FWNZS6y8bdEK5meyo2fBmRE1gULhMVh/M4W6aYZE9ZT373lVN+xFZ1CRE+qhTI1ndOwTnorWNKZTHYoBFM8rso3H0/7+XoE7Z9d7uctWbJ2ntfepNLHxXV0L1puITkMedjzEFj6e2OeeLu0ffoPhgoRI8StAz+8b1gDHMJozJ8aIZCL46rDOmKbfH/ihCOrt22PGJix5FeC/MnsB0UnsWqovjT8t+D6112mjBl/vGFMNIfileookVr9z6IdfqrCk65Xdequ3NaQ+AaTWbGBtFe57w2W2NF7lKIBWB60Tq+TS98=
